default:
  target: dev
  outputs:
    default:
      catalog: '{{ env_var(''DBT_CATALOG'') }}'
      host: '{{ env_var(''DATABRICKS_HOST'') }}'
      http_path: '{{ env_var(''DBT_HTTP_PATH'') }}'
      schema: bronze
      threads: 8
      token: '{{ env_var(''DATABRICKS_TOKEN'') }}'
      type: databricks
