# This workflow validates, deploys, and runs the specified bundle
# within a production target named "prod".
name: "Production deployment"

# Ensure that only a single job or workflow using the same concurrency group
# runs at a time.
concurrency: 1

# Trigger this workflow whenever a pull request is pushed to the repo's
# main branch.
on:
  push:
    branches:
      - dev

#Only deploy step needed in PRD as job is normally scheduled

jobs:
  deploy:
    name: "Deploy bundle"
    runs-on: ubuntu-latest
    environment: prod
    env:
      DBT_ENV_SECRET_DB_TOKEN: ${{ secrets.SP_TOKEN }}
      DATABRICKS_BUNDLE_ENV:  ${{ vars.DATABRICKS_BUNDLE_ENV }}
      DBT_CATALOG:  ${{ vars.DBT_CATALOG }}
      DATABRICKS_HOST:  ${{ vars.DATABRICKS_HOST }}
      DBT_HTTP_PATH:  ${{ vars.DBT_HTTP_PATH }}
      DBT_PROFILES_DIR: ./
    steps:
      # Check out this repo, so that this workflow can access it.
      - uses: actions/checkout@v3

      # Download the Databricks CLI.
      # See https://github.com/databricks/setup-cli
      - uses: databricks/setup-cli@main

      # Deploy the bundle to the "prod" target as defined
      # in the bundle's settings file.
      - run: databricks bundle deploy
        working-directory: .
