# This workflow validates, deploys, and runs the specified bundle
# within a pre-production target named "qa".
name: "DBT DSS Session example"

# Ensure that only a single job or workflow using the same concurrency group
# runs at a time.
concurrency: "1"

# Trigger this workflow whenever a pull request is opened against the repo's
# main branch or an existing pull request's head branch is updated.
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - dev

jobs:
  # Used by the "pipeline_update" job to deploy the bundle.
  # Bundle validation is automatically performed as part of this deployment.
  # If validation fails, this workflow fails.
  deploy:
    name: "Deploy bundle"
    runs-on: ubuntu-latest
    env:
      DATABRICKS_TOKEN: ${{ secrets.SP_TOKEN }}
      DATABRICKS_BUNDLE_ENV: qa
      DBT_CATALOG: qa_dss_dbt_catalog
      DBT_WORKSPACE: adb-984752964297111.11.azuredatabricks.net
      DBT_HTTP_PATH: /sql/1.0/warehouses/2e78d4a8647e3893
      DBT_PROFILES_DIR: ./
    steps:
      # Check out this repo, so that this workflow can access it.
      - uses: actions/checkout@v3

      # Download the Databricks CLI.
      # See https://github.com/databricks/setup-cli
      - uses: databricks/setup-cli@main

      - uses: actions/setup-python@v1
        with:
          python-version: "3.9.x"

      - name: Install dependencies
        run: |
            pip install pipenv
            pipenv install
            pipenv shell
            dbt deps --target dev
        
      - name: Build dbt models
        run: dbt build --target dev

      # Deploy the bundle to the "qa" target as defined
      # in the bundle's settings file.
      - run: databricks bundle deploy
        working-directory: .

